API_ID: 11849455
API_HASH: 0956032efc5694f60156fe65f9c19764
BOT_TOKEN: 5752243326:AAHvTPls-tnNkyrOTpOlguEX6PqZYnPHfXM


MONGO_URL: mongodb+srv://root:UnXrKDvP63NIIpKh@cluster0.7qbzdm3.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-19489.c9.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 19489
REDIS_PASS: Zb2RawbHx5eIadRmFvJUL4xSQAmPVv2P

SESSION_API_ID: 11849455
SESSION_API_HASH: 0956032efc5694f60156fe65f9c19764
SESSION_STRING: 1AZWarzUBu3llHWYfeNQywoKh8dB2N6hmFqesjNk2VavYU_HlO8Z06URLkUTJhjAGXprOzjqQIKH-MJ78ssOjLW4HyCjVvd4I5gfmH38u413E2fzSItUVXLnGaruIdbGZaF1oxAcSNp8vzl8PQeZADRHb1yNiUy9RKBwWfcqrD6rjZz4abM9NrIrtWwROt7EBwWCJDcujzvAc5Ng801D73gqBxBZMq3mEo71iF4vseEaBZX1BSVZQ3NhWt0WFJgFgGQ1w_v1R80R4D0kAz0p6jFvWQSqr0wrwyb16JZegKzyFSLXNouMuOJ26Zy_UYoP1I0yC9EgDfuOzgx-UvbXzxmp-2Jlswac=

ADMINS: 
  - 5019536742

OWNER: 5019536742

BOT_PIC: https://telegra.ph/file/162f07523999ce9b8af77.jpg
OWNER_PIC: https://telegra.ph/file/162f07523999ce9b8af77.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: -833549479



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "$"
  - "?"

