API_ID: 10738933
API_HASH: d26cadc9215f79d6e8f1cca1c4a8f04b
BOT_TOKEN: 5902161959:AAGXf6w5daxy7WU--Cmta3Y1XCmY65DCpHI


MONGO_URL: mongodb+srv://root:UnXrKDvP63NIIpKh@cluster0.7qbzdm3.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-19860.c8.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT: 19860
REDIS_PASS: 7Q4onDm2yyYwCM8EGDwyz0EUR59ej7Pz

SESSION_API_ID: 10738933
SESSION_API_HASH: d26cadc9215f79d6e8f1cca1c4a8f04b
SESSION_STRING: 1AZWarzMBu0wHM3dXs22JBShmYo0NPvuKv76KMioaxYAJaSqBfa2BmnMNQICskN_ibcICH_IjwBgh8RlQrevvD37ymzb4wz98Vv0jZmXXX6IKqSEiCylWE3-Un2bNjLdAjpLntNvu82DB6B3DEppYjZgYzefrRPelLn7Q08yTQ6OQfRlIBx0H_u2eNQfzT_hGWNiCeBu3UkC6UB4um7kRpbTdkKjvOxGPx8eYIG2mtSSEZkpXjcYHf63XDW0g2iMt1WTJuDf8_2lozhcSXhg1kAuhSOTuYozfD9SZvzLMZWloYEYu4aauOTO2WhhpomuJTBYAVMq3GzQv8ITftrqXR9-M2OHDx7M=-MJ78ssOjLW4HyCjVvd4I5gfmH38u413E2fzSItUVXLnGaruIdbGZaF1oxAcSNp8vzl8PQeZADRHb1yNiUy9RKBwWfcqrD6rjZz4abM9NrIrtWwROt7EBwWCJDcujzvAc5Ng801D73gqBxBZMq3mEo71iF4vseEaBZX1BSVZQ3NhWt0WFJgFgGQ1w_v1R80R4D0kAz0p6jFvWQSqr0wrwyb16JZegKzyFSLXNouMuOJ26Zy_UYoP1I0yC9EgDfuOzgx-UvbXzxmp-2Jlswac=

ADMINS: 
  - 5019536742

OWNER: 5019536742

BOT_PIC: https://telegra.ph/file/162f07523999ce9b8af77.jpg
OWNER_PIC: https://telegra.ph/file/162f07523999ce9b8af77.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: -833549479



HANDLERS: 
  - "."
  - " "
  - "/"
  - "$"
  - "?"

