API_ID: 10738933
API_HASH: d26cadc9215f79d6e8f1cca1c4a8f04b
BOT_TOKEN: 5902161959:AAGXf6w5daxy7WU--Cmta3Y1XCmY65DCpHI


MONGO_URL: mongodb+srv://root:zXIz54dq1VEqIEJo@root.bxe6t3t.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-12364.c84.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 12364
REDIS_PASS: T8Ymh5ZY56VejX38y5i2m5mqOOcRs1My

SESSION_API_ID: 10738933
SESSION_API_HASH: d26cadc9215f79d6e8f1cca1c4a8f04b
SESSION_STRING: 1AZWarzMBu0wHM3dXs22JBShmYo0NPvuKv76KMioaxYAJaSqBfa2BmnMNQICskN_ibcICH_IjwBgh8RlQrevvD37ymzb4wz98Vv0jZmXXX6IKqSEiCylWE3-Un2bNjLdAjpLntNvu82DB6B3DEppYjZgYzefrRPelLn7Q08yTQ6OQfRlIBx0H_u2eNQfzT_hGWNiCeBu3UkC6UB4um7kRpbTdkKjvOxGPx8eYIG2mtSSEZkpXjcYHf63XDW0g2iMt1WTJuDf8_2lozhcSXhg1kAuhSOTuYozfD9SZvzLMZWloYEYu4aauOTO2WhhpomuJTBYAVMq3GzQv8ITftrqXR9-M2OHDx7M=

ADMINS: 
  - 1402370393

OWNER: 1402370393

BOT_PIC: https://telegra.ph/file/162f07523999ce9b8af77.jpg
OWNER_PIC: https://telegra.ph/file/162f07523999ce9b8af77.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: -833549479



HANDLERS: 
  - "."
  - " "
  - "/"
  - "$"
  - "?"

